services:
  frontend:
    build: ./frontend
    image: pathways-frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - VITE_ENV=production
    # env_file:
    #   - ./frontend/.env.production
  backend:
    build: ./backend
    image: pathways-backend:latest
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./shared-data:/app/shared-data:ro
    # env_file:
    #   - ./backend/.env.production
    environment:
      - ENV=production
      - PYTHONUNBUFFERED=1
volumes:
  shared-data:
